version: '3'
services:
    web:
        container_name: wills_web_demo
        image: 
            nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./code :/code
    